export type SetupStats = { vehicles: number; drivers: number; routes: number; jobs: number; fuelEntries: number; clients: number; documents: number; invoices: number };
type Step = { key: keyof SetupStats; title: string; summary: string; benefit: string; tasks: string[]; criteria: string; tip: string; href: string; action: string; optional?: boolean };
export const SETUP_STEPS: Step[] = [
  {key:"vehicles",title:"Araçlar",summary:"İlk araç kaydınızı oluşturun.",benefit:"Sefer, şoför ve gider kayıtlarını doğru araçla ilişkilendirmenizi sağlar.",tasks:["Araçlar ekranında Araç Ekle seçeneğini açın.","Plaka, model ve kapasite bilgilerini kontrol ederek kaydedin."],criteria:"Firmaya ait en az bir araç kaydı bulunması.",tip:"Bir araçla başlayabilirsiniz. Toplu aktarım için önce Excel şablonunu indirip alanları inceleyin.",href:"/panel/araclar",action:"Araçları aç"},
  {key:"drivers",title:"Şoförler",summary:"Ekibinizi kaydedin ve erişim bilgilerini hazırlayın.",benefit:"Şoförleri seferlere ve araçlara atayabilmeniz için temel kayıt oluşturur.",tasks:["Şoför ekleme formunda ad ve iletişim bilgilerini girin.","Ehliyet bilgilerini kontrol edin. Mobil erişim gerekiyorsa kişiye özel giriş bilgisi belirleyin."],criteria:"Firmaya ait en az bir aktif şoför kaydı bulunması.",tip:"Şifreleri ortak kullanmayın. Şoför kaydı tek başına mobil cihaz testinin tamamlandığı anlamına gelmez.",href:"/panel/soforler",action:"Şoförleri aç"},
  {key:"routes",title:"Güzergâhlar",optional:true,summary:"Sabit okul veya personel hatlarınızı tanımlayın.",benefit:"Durakları, saatleri ve araç/şoför atamalarını aynı hat üzerinde toplar.",tasks:["Yeni güzergâh oluşturup türünü seçin.","Durakları ve saatleri girin, uygun araç ile şoförü atayın."],criteria:"En az bir aktif, araç ve şoför atanmış, durak içeren güzergâh bulunması.",tip:"Sabit hatla çalışmıyorsanız bu adımı sonraya bırakabilirsiniz.",href:"/panel/guzergahlar",action:"Güzergâhları aç"},
  {key:"documents",title:"Belge tarihleri",summary:"Araçlarınızın takip edilecek tarihlerini girin.",benefit:"Yaklaşan veya geçmiş tarihler için paneldeki belge takibini besler.",tasks:["Araç listesinden bir aracın detayını açın.","Muayene, sigorta veya güzergâh izni tarihini belgedeki bilgiyle karşılaştırıp kaydedin."],criteria:"En az bir araçta muayene, sigorta veya güzergâh izni tarihi bulunması.",tip:"Dosya yüklemek tarih girmekle aynı şey değildir. Sistem resmi belge geçerliliğini doğrulamaz.",href:"/panel/araclar",action:"Araç belgelerine git"},
  {key:"jobs",title:"İlk sefer",summary:"Planlanan veya yapılan bir seferi kaydedin.",benefit:"Günlük işlerinizi ve sefer durumlarını panelden takip etmeye başlamanızı sağlar.",tasks:["İşler ve seferler ekranında yeni kayıt açın.","Tarih, saat, araç ve şoför bilgilerini kontrol ederek kaydedin."],criteria:"Firmaya ait en az bir sefer kaydı bulunması.",tip:"Gerçek operasyonu yansıtan kayıt girin. Bu ölçüt tüm seferlerin atamalarını veya tamamlanmasını doğrulamaz.",href:"/panel/isler",action:"Seferleri aç"},
  {key:"clients",title:"Müşteri firmalar",optional:true,summary:"Fatura ve ödeme takibi yapacağınız müşterileri tanımlayın.",benefit:"Ticari kayıtların ilgili müşteriyle eşleşmesine yardımcı olur.",tasks:["Faturalar ekranından müşteri firma ekleme alanını açın.","Firma unvanını ve gerekli ticari bilgileri doğrulayıp kaydedin."],criteria:"En az bir müşteri firma kaydı bulunması.",tip:"Müşteri firması kaydı, sisteme giriş yapan işletme hesabınızdan farklıdır.",href:"/panel/faturalar",action:"Müşteri firmalarını aç"},
  {key:"fuelEntries",title:"Yakıt kayıtları",optional:true,summary:"İlk yakıt alımını ilgili araca bağlayın.",benefit:"Araç bazında yakıt gideri takibi için veri oluşturur.",tasks:["Yakıt ekranında ilgili aracı seçin.","Alım tarihi, miktar ve tutarı belgeyle karşılaştırarak kaydedin."],criteria:"Firmaya ait en az bir yakıt kaydı bulunması.",tip:"Anlamlı tüketim karşılaştırması için düzenli ve doğru kilometre/miktar kayıtları gerekir.",href:"/panel/yakit",action:"Yakıt ekranını aç"},
  {key:"invoices",title:"Faturalar",optional:true,summary:"İlk gerçek fatura kaydınızı ekleyin.",benefit:"Faturaları müşteri ve ödeme takibiyle birlikte izleyebilmenizi sağlar.",tasks:["Faturalar ekranından fatura ekleme veya PDF yükleme alanını açın.","Müşteri, tarih ve tutarı kontrol edin. PDF'den okunan alanları doğrulayın."],criteria:"Firmaya ait en az bir fatura kaydı bulunması.",tip:"Müşteri veya sefer eklemek bu adımı tamamlamaz. Bu ekran resmi e-fatura düzenleme hizmeti olarak değerlendirilmemelidir.",href:"/panel/faturalar",action:"Faturaları aç"},
];
export function isSetupStats(value: unknown): value is SetupStats {
  if (!value || typeof value !== "object") return false;
  return SETUP_STEPS.every(({key}) => { const n = (value as Record<string, unknown>)[key]; return typeof n === "number" && Number.isSafeInteger(n) && n >= 0; });
}
