ALTER TABLE "Driver" ADD COLUMN "latitude" DOUBLE PRECISION;
ALTER TABLE "Driver" ADD COLUMN "longitude" DOUBLE PRECISION;
ALTER TABLE "Driver" ADD COLUMN "lastLocationAt" TIMESTAMP(3);
ALTER TABLE "Driver" ADD COLUMN "isTracking" BOOLEAN NOT NULL DEFAULT false;
